export const interviewQuest = [
    'What is the difference between constructor and ngOnInit?',
    'What is the difference between components and directives?',
    'What is the difference between ElementRef, TemplateRef, and viewContainerRef?',
    'What is the difference between ng-content,ng-template, and ng-container?',
    'What is the difference between view-child and content-child?',
    'What is the difference between component view, host view, and embedded view?',
    'What is the difference between debounce time and throttle time?',
    'What is the difference between forEach and map?',
    'What is the difference between ng-content and ng-templateoutlet?',
    'What is the difference between forchild vs forroot?',
    'Why we use pipe operators in RXJS. What is the use of it?',
    'What is the difference between using the Async pipe vs the subscribe function in the Angular application?',
    'What is the difference between promise and observable?',
    'What is the difference between Event Emitter and Subjects?',
    'What is the difference between Observable and Subject?',
    'What is the difference between Activated Route vs Activated route Snapshot?',
    'Discuss different kinds of loading strategies used in your Angular application?',
    'What is Metadata?',
    'What is routerlinkActive use for?',
    'Where we use generics in Angular?',
    'What is the wild card route?',
    'What is the difference between ngIf and hidden?',
    'What is a router outlet?',
    'What is the Router state?',
    'What is an Active route?',
    'Explain different injections in angular?',
    'What is the best way to implement translations in angular?',
    'Explain different routing params in Angular?',
    'What is a virtual scroll in Angular?',
    'What is the difference between route param vs query param?',
    'Explain different guards supported in Angular?',
    'Which RXJS operators used for transforming or manipulating data?',
    'What is the best way to lazy load the component?',
    'What is the way we can display the app version in Angular?',
    'What are the generators in ES6?',
    'Explain the Error mechanism in your application?',
    'What is bootstrapping in angular?',
    'What are Angular elements?, why we use it?',
    'What is the difference between the arrow function and regular functions?',
    'What is the difference between Functional vs Object Oriented Programming language?, Which one you prefer and why?',
    'What is the difference between JavaScript and TypeScript?',
    'What do you know about Closures?',
    'What is the difference between Template Driven forms and Reactive Forms?',
    'What are different Kinds of Bindings possible in Angular?',
    'Which RXJS Operators you use mostly to handle HTTP services?',
    'What is the difference between mergemap/switchmap/concatmap and exhaustmap and where we can use them?',
    'Discuss different decorators in Angular?',
    'Explain different lifecycle methods in Angular?',
    'Explain the hierarchy of the Angular Life cycle hooks?',
    'What is renderer 2?',
    'What is the difference between renderer and ElementRef?',
    'What is Zone.js?',
    'What is Race Condition in Angular?',
    'What is a callback, Promises and Async/Await in Angular?',
    'What is Host binding and Host Listener in Angular?',
    'What is dependency injection in Angular?',
    'Explain the digest cycle/Change detection Cycle in Angular?',
    'What is the difference between markForCheck and detectchanges?',
    'What are the ways to clone the object?',
    'Explain how Angular application loads/Initialize?',
    'How to detect non-primitive type data when an @Input() value changes in Angular?',
    'What are the different Encapsulation strategies in Angular?',
    'What is Shadow DOM in Angular?',
    'Explain different types of directives in Angular?',
    'What is the best way to unsubscribe from the observable?',
    'What is an Angular language service?',
    'Difference between Angular’s canLoad and canActivate?',
    'How to check if route changes in Angular?',
    'Explain different router events in Angular?',
    'What are the manual ways to trigger change detection in Angular?',
    'Discuss different pipes in Angular?',
    'What are the best security practices you follow in Angular?',
    'What is the best way to improve angular performance?',
    'Have you handled the expression that has changed after it was checked error?',
    'What is the way to handle if one module is already loaded?',
    'Have you created a custom library in Angular?',
    'What are the ways you analyze the memory in Application?',
    'Explain different router events in Angular?',
    'What are the data types in Angular?',
    'What is the best way to optimize Async Validators?',
    'What is Enums in Angular?',
    'What is the difference between find and filter in JavaScript?',
    'Prevent Multiple Service Calls on Button Click in Angular?',
    'How to pass data between components in Angular?',
    'What is the difference between (change) vs (ngModelChange)?',
    'What is the difference between declarations, providers, and imports?',
    'How to Override CSS in Angular Component Libraries (such as Angular Material)?',
    'How to do dynamically bind string from component to HTML?',
    'How to set ngFor and ngIf on the same element?',
    'Can you give an example of built-in validators?',
    'What is an entry component?',
    'What is observable and observer in Angular?',
    'What are service workers in Angular?',
    'How to update all libraries with the latest version in Angular?',
    'What is an interceptor?, How you configured your application',
    'Explain the architecture of your Angular Application?',
    'Explain some methods you mostly use to test the Angular Components?',
    'What are the different SCSS functions you used in your application?',
    'What is the difference between OnPush and default change detection?',
    'How can you bind data to templates?',
    'What is the difference between takeWhile and takeUntil RXJS Operator?',
    'What is the difference between BehaviourSubject/Subject/ReplaySubject and Async Subject?',
    'Explain practical usage of the ng-temple,ng-content,ng-container, and ng-templateOutlet?',
    'Why we use the forchild and forroot method in route?, What is its usage?',
    'How to update all angular libraries to the latest versions?',
    'What is a content projection in Angular and How it works?',
    'What is the APP_INITILIZER in Angular and What it is used for?',
    'Explain route reuse strategies in Angular Application?',
    'How does Server-Side rendering work in Angular?',
    'What are service workers in Angular?, How to use them?'
]